#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "ombi"
name = "Ombi"
description.en = "Media request tool on Plex/Emby/Jellyfin"
description.fr = "Outil de demande de médias sur Plex/Emby/Jellyfin"

version = "4.53.5~ynh1"

maintainers = []

[upstream]
license = "GPL-2.0"
website = "https://ombi.io/"
demo = "https://app.ombi.io/landingpage"
admindoc = "https://docs.ombi.app/guides/installation/"
code = "https://github.com/Ombi-app/Ombi"
fund ="https://www.paypal.com/paypalme/PlexRequestsNet"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/ombi"
    
    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        amd64.url = "https://github.com/Ombi-app/Ombi/releases/download/v4.53.5/linux-x64.tar.gz"
        amd64.sha256 = "1a09eb8461ad99d9263db1f5572c61888e3cdde9e791453c6eef9d4c0fd83c14"
        arm64.url = "https://github.com/Ombi-app/Ombi/releases/download/v4.53.5/linux-arm64.tar.gz"
        arm64.sha256 = "99906da82c1a1866b3bd61afe1614b0c7160eb0b4dd9c792e72dd4b38e5f83b8"
        armhf.url = "https://github.com/Ombi-app/Ombi/releases/download/v4.53.5/linux-arm.tar.gz"
        armhf.sha256 = "8e29a75bf43e03f8eaadfd0f1d9a13e9b8e510d473de956a104dc9920f6a259b"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.arm64 = "linux-arm64\\.tar\\.gz"
        autoupdate.asset.amd64 = "linux-x64\\.tar\\.gz"
        autoupdate.asset.armhf = "linux-arm\\.tar\\.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    api.url = "/api"
    api.auth_header = false
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    login.url = "/login"
    login.auth_header = false
    login.show_tile = false

    [resources.ports]

    [resources.apt]
    packages = "mariadb-server"

    [resources.database]
    type = "mysql"
